server:
    port: 8081
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/econtreras?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: econtreras_user
    password: abcd.123
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB
      location: ${java.io.tmpdir}
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        starttls:
          enable: true
          required: true
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: enriquev.rodriguez@gmail.com
    password: 'Mi#es064'
file:
    upload-dir: /home/enrique/uploads
api:
  messages:
    already-exist: El departamento que intenta agregar ya existe!
    internal-server-error: Ocurrió un error inesperado

userTryLoginLimit: 3
jackson:
  date-format: yyyy-MM-dd
  timestamp-format: yyyy-MM-dd HH:mm:ss
  serialization:
    write-dates-as-timestamps: false